version: "3.9"

services:
  db:
    image: postgres:16
    container_name: task_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_app
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kevin -d task_app"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      target: development
    container_name: task_app_api
    environment:
      DATABASE_URL: "postgresql://kevin:1234@db:5432/task_app?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src  # Mount the source code
      - /app/node_modules  # Ensure node_modules is accessible
    command: npm run start:dev  # Use the development command

volumes:
  db_data: