FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache docker-cli
COPY package*.json ./
COPY prisma ./prisma
RUN npm install
COPY . .
RUN npm install -g nodemon ts-node typescript
EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm run start:dev"]