export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
export const CHALLENGE_REPOSITORY = Symbol('CHALLENGE_REPOSITORY');
export const SUBMISSION_REPOSITORY = Symbol('SUBMISSION_REPOSITORY');
